spring.application.name=bai9_vd1_2
server.port=8081
# Thymeleaf
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
#kết nối database
spring.datasource.url=jdbc:h2:mem:bai9_vd1_2;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
#JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#Hibernate ddl auto (create, create-drop, update, none)
spring.jpa.hibernate.ddl-auto=create-drop
# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB